name: Publish
on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish on NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Generate types
        run: yarn tsc

      - name: Build
        run: yarn build

      - run: ci
      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


#      - name: Publish if version has been updated
#        uses: pascalgn/npm-publish-action@1.3.9
#        with:
#         tag_name: "v%s"
#          tag_message: "v%s"
#          commit_pattern: "^Release (\\S+)"
#        env: # More info about the environment variables in the README
#          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}